quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_user}
    jdbc:
      url: jdbc:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:app_user}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
  http:
    port: 8080
  oidc:
    enabled: true
    application-type: SERVICE
    auth-base-url: ${OIDC_SERVER_URL:http://localhost:8090/auth}
    auth-server-url: ${quarkus.oidc.auth-base-url}/realms/${quarkus.oidc.realm-name}
    admin-cli-id: ${OIDC_ADMIN_CLI_ID:admin-cli}
    client-id: ${OIDC_CLIENT_ID:backend-client}
    realm-name: ${OIDC_REALM_NAME:app}
    roles:
      role-claim-path: ${OIDC_ROLES_PATH:roles}
    introspection-path: /protocol/openid-connect/userinfo
    jwks-path: /protocol/openid-connect/certs
    token:
      principal-claim: preferred_username
    credentials:
      secret: ${OIDC_CLIENT_SECRET:109864f5-fc15-4eef-b4d9-5ce3bf789c34}
      admin-cli-secret: ${OIDC_ADMIN_CLI_SECRET:64130375-5e1a-4b13-b8f4-fad8cf039e16}
mp:
  openapi:
    extensions:
      smallrye:
        info:
          version: 1.0
          description: Users API
          contact:
            email: marco.bungart@consol.de
            name: Marco Bungart