quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_user}
    jdbc:
      url: jdbc:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:app_user}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
  http:
    port: 8080
mp:
  openapi:
    extensions:
      smallrye:
        info:
          version: 1.0
          description: Users API
          contact:
            email: marco.bungart@consol.de
            name: Marco Bungart