quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_user}
    jdbc:
      url: jdbc:tracing:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:app_user}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
      driver: io.opentracing.contrib.jdbc.TracingDriver
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  http:
    port: ${PORT:8080}
  jaeger:
    enabled: true
    endpoint: ${TRACING_ENDPOINT:http://localhost:14268/api/traces}
    sampler-type: const
    sampler-param: 1
    service-name: user-service
mp:
  openapi:
    extensions:
      smallrye:
        info:
          version: 1.0
          description: Users API
          contact:
            email: marco.bungart@consol.de
            name: Marco Bungart
color-rest/mp-rest/url: ${COLOR_URL:http://localhost:8081}
color-rest/mp-rest/scope: javax.inject.Singleton