version: '3.7'
services:
  dbms-service:
    image: postgres:13.1@sha256:42c1b84839db8f78bb66b3d6f300a88a8517895454df4a1cb2f101dfae609769
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '15432:5432'
  oidc-service:
    image: jboss/keycloak:11.0.3@sha256:5242f5e0d7b22b9947c275f6ad9f92d7e9a870540cc6a6042b85185115e1af2f
    volumes:
      - ./keycloak/app.json:/tmp/app.json
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=dbms-service
      - DB_PORT=5432
      - DB_USER=keycloak_user
      - DB_PASSWORD=keycloak_user
      - DB_DATABASE=keycloak
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/tmp/app.json
    ports:
      - '8090:8080'
    depends_on:
      - dbms-service